import webserver

class TasmoClawUI
  def chat_page()
    webserver.content_start('TasmoClaw')
    webserver.content_send_style()
    webserver.content_send('<style>')
    webserver.content_send(':root{--tc-bg1:#111a22;--tc-bg2:#0b1018;--tc-card:#121b26;--tc-border:#2c3d53;--tc-text:#eef3f8;--tc-muted:#91a4b9;--tc-accent:#38bdf8;--tc-accent2:#22c55e;--tc-good:#34d399;--tc-bad:#f87171;}')
    webserver.content_send('.tc-wrap{max-width:980px;margin:0 auto;padding:10px;box-sizing:border-box;font-family:system-ui,-apple-system,Segoe UI,Roboto,Ubuntu,sans-serif;color:var(--tc-text);overflow-x:hidden}')
    webserver.content_send('.tc-top{display:flex;flex-direction:column;gap:10px;margin-bottom:10px}')
    webserver.content_send('.tc-title{font-size:1.25rem;margin:0;color:#fff;letter-spacing:0.2px}')
    webserver.content_send('.tc-nav{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px}.tc-btn{display:inline-flex;align-items:center;justify-content:center;border-radius:10px;border:1px solid var(--tc-border);padding:10px 8px;background:#17314f;color:#e8f0ff;text-decoration:none;min-height:40px;min-width:0;box-sizing:border-box;font-weight:600;font-size:13px;white-space:normal;text-align:center}')
    webserver.content_send('.tc-status{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}')
    webserver.content_send('.tc-panel{background:linear-gradient(160deg,var(--tc-bg1),var(--tc-bg2));border:1px solid var(--tc-border);border-radius:12px;padding:10px;min-width:0}')
    webserver.content_send('.tc-meta{display:grid;grid-template-columns:1fr;gap:6px}')
    webserver.content_send('.tc-meta-row{display:flex;align-items:flex-start;justify-content:space-between;gap:10px;padding:6px 8px;background:#0f1a27;border:1px solid var(--tc-border);border-radius:9px;min-width:0}')
    webserver.content_send('.tc-pill{font-size:10px;color:#9bc4ff;min-width:74px;flex:0 0 auto;flex-shrink:0}')
    webserver.content_send('.tc-pill-val{color:#ecf2fb;text-align:left;overflow-wrap:anywhere;word-break:break-word;white-space:normal;min-width:0;flex:1 1 auto}')
    webserver.content_send('.tc-chat{display:flex;flex-direction:column;gap:8px;min-height:260px;max-height:55vh;background:#09111a;border:1px solid var(--tc-border);border-radius:12px;padding:8px;overflow:auto;min-width:0}')
    webserver.content_send('.tc-line{display:block;padding:6px 8px;border-radius:10px;border:1px solid #213a54;white-space:pre-wrap;overflow-wrap:anywhere;line-height:1.35}')
    webserver.content_send('.tc-line-role{font-size:10px;color:#9bc4ff;text-transform:uppercase;letter-spacing:0.4px;margin-bottom:4px}')
    webserver.content_send('.tc-line pre{margin:0;white-space:pre-wrap;font:12px ui-monospace,SFMono-Regular,Menlo,monospace;line-height:1.35;overflow-wrap:anywhere;color:#e5eef8}')
    webserver.content_send('.tc-line.tc-user{background:#10253e}.tc-line.tc-assistant{background:#0d2420;border-color:#205c4a}.tc-line.tc-tool{background:#181f2a;border-color:#54657a}.tc-line.tc-approval{background:#35220f;border-color:#8f6a14}')
    webserver.content_send('.tc-thinking{display:flex;align-items:center;gap:10px;background:linear-gradient(135deg,#0a1826,#0d2a32);border-color:#1f8aa6;box-shadow:0 0 18px rgba(56,189,248,.18) inset}.tc-orbit{width:22px;height:22px;border-radius:50%;border:2px solid rgba(56,189,248,.24);border-top-color:#38bdf8;border-right-color:#22c55e;animation:tcspin .85s linear infinite;box-shadow:0 0 14px rgba(56,189,248,.4)}.tc-thinking-text{font:12px ui-monospace,SFMono-Regular,Menlo,monospace;color:#d8f7ff;letter-spacing:.4px}.tc-dots span{display:inline-block;animation:tcdot 1.05s infinite}.tc-dots span:nth-child(2){animation-delay:.18s}.tc-dots span:nth-child(3){animation-delay:.36s}@keyframes tcspin{to{transform:rotate(360deg)}}@keyframes tcdot{0%,80%,100%{opacity:.2;transform:translateY(0)}40%{opacity:1;transform:translateY(-3px)}}')
    webserver.content_send('.tc-compose{display:grid;grid-template-columns:1fr auto;gap:8px;margin-top:8px}')
    webserver.content_send('.tc-message{width:100%;box-sizing:border-box;min-height:72px;height:72px;max-height:120px;resize:vertical;padding:10px;background:#0f1722;color:#e8eff8;border:1px solid var(--tc-border);border-radius:10px;font:13px/1.3 inherit}')
    webserver.content_send('button{min-height:40px;border-radius:10px!important;padding:0 12px;font-weight:700}')
    webserver.content_send('.tc-err{color:var(--tc-bad);min-height:18px;margin-top:6px;font-size:12px}')
    webserver.content_send('.tc-pending{border:1px dashed var(--tc-accent2);padding:8px;border-radius:12px;margin-top:8px}')
    webserver.content_send('.tc-pending pre{white-space:pre-wrap;overflow:auto;max-height:160px;overflow-wrap:anywhere;margin:6px 0 0 0}')
    webserver.content_send('@media (max-width:640px){.tc-status{grid-template-columns:1fr}.tc-compose{grid-template-columns:1fr}.tc-compose button{width:100%}}')
    webserver.content_send('@media (max-width:640px){.tc-nav{grid-template-columns:repeat(2,minmax(0,1fr))}.tc-status{margin-bottom:0}.tc-chat{max-height:52vh}}')
    webserver.content_send('@media (max-width:390px){.tc-wrap{padding:8px}.tc-title{font-size:1.1rem}.tc-nav{grid-template-columns:1fr 1fr}.tc-meta-row{flex-direction:column;gap:4px}.tc-pill-val{min-width:auto}}')
    webserver.content_send('</style>')
    webserver.content_send('<div class="tc-wrap">')
    webserver.content_send('<div class="tc-top"><h2 class="tc-title">TasmoClaw</h2><div class="tc-nav"><a class="tc-btn" href="/mn">Tools menu</a> <a class="tc-btn" href="/tasmoclaw/config">Config</a> <button class="tc-btn" id="tc_clear">Clear</button></div></div>')
    webserver.content_send('<div class="tc-status">')
    webserver.content_send('<div class="tc-panel"><div class="tc-meta"><div class="tc-meta-row"><span class="tc-pill">Model</span><span class="tc-pill-val" id="tc_model"></span></div><div class="tc-meta-row"><span class="tc-pill">Endpoint</span><span class="tc-pill-val" id="tc_endpoint"></span></div></div></div>')
    webserver.content_send('<div class="tc-panel"><div class="tc-meta"><div class="tc-meta-row"><span class="tc-pill">Heap</span><span class="tc-pill-val" id="tc_heap"></span></div><div class="tc-meta-row"><span class="tc-pill">WiFi</span><span class="tc-pill-val" id="tc_wifi"></span></div></div></div>')
    webserver.content_send('</div>')
    webserver.content_send('<div id="tc_chat" class="tc-chat"></div>')
    webserver.content_send('<div class="tc-compose"><textarea id="tc_message" class="tc-message" placeholder="Ask TasmoClaw anything..."></textarea><button id="tc_send">Send</button></div>')
    webserver.content_send('<div id="tc_error" class="tc-err"></div>')
    webserver.content_send('<div id="tc_pending" class="tc-panel tc-pending" style="display:none"><h4 style="margin:0 0 6px 0">Pending approval</h4><pre id="tc_pending_json"></pre><div style="display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:8px"><button id="tc_approve">Approve</button> <button id="tc_reject">Reject</button></div></div>')
    webserver.content_send('</div>')

    webserver.content_send('<script>const tcJson=(u,o)=>fetch(u,o).then(r=>r.json());const chatEl=document.getElementById("tc_chat");const sendBtn=document.getElementById("tc_send");const msgEl=document.getElementById("tc_message");const errEl=document.getElementById("tc_error");let thinkingEl=null;function row(role,text){const r=document.createElement("div");r.className="tc-line tc-"+(role=="assistant"?"assistant":role=="tool"?"tool":role=="approval"?"approval":"user");const rr=document.createElement("div");rr.className="tc-line-role";rr.textContent=role;const pre=document.createElement("pre");pre.textContent=text||"";r.appendChild(rr);r.appendChild(pre);chatEl.appendChild(r);return r;}function addLine(role,text){row(role,text);chatEl.scrollTop=chatEl.scrollHeight;}function showThinking(){hideThinking();const r=document.createElement("div");r.className="tc-line tc-thinking";const orb=document.createElement("div");orb.className="tc-orbit";const tx=document.createElement("div");tx.className="tc-thinking-text";tx.innerHTML="TasmoClaw thinking <span class=\\"tc-dots\\"><span>.</span><span>.</span><span>.</span></span>";r.appendChild(orb);r.appendChild(tx);chatEl.appendChild(r);thinkingEl=r;chatEl.scrollTop=chatEl.scrollHeight;}function hideThinking(){if(thinkingEl&&thinkingEl.parentNode){thinkingEl.parentNode.removeChild(thinkingEl);}thinkingEl=null;}function showErr(t){errEl.textContent=t||"";}function showPending(x){const panel=document.getElementById("tc_pending");const pre=document.getElementById("tc_pending_json");if(!x||!x.pending){panel.style.display="none";pre.textContent="";return;}panel.style.display="block";pre.textContent=JSON.stringify(x.pending,null,2);}function refreshStatus(){tcJson("/tasmoclaw/api/status").then(s=>{if(s.ok){document.getElementById("tc_model").textContent=s.model||"";document.getElementById("tc_endpoint").textContent=s.api_url||"";document.getElementById("tc_heap").textContent=JSON.stringify(s.heap);document.getElementById("tc_wifi").textContent=s.wifi&&s.wifi.ip?s.wifi.ip:"off";}}).catch(e=>showErr(String(e)));}function refreshHistory(){tcJson("/tasmoclaw/api/history").then(x=>{chatEl.textContent="";thinkingEl=null;(x.history||[]).forEach(m=>{const role=m.role||"assistant";addLine(role,m.content)});}).catch(e=>showErr(String(e)));}function refreshPending(){tcJson("/tasmoclaw/api/pending").then(showPending).catch(e=>showErr(String(e)));}function refreshAll(){refreshStatus();refreshHistory();refreshPending();}function send(){const v=msgEl.value.trim();if(!v||sendBtn.disabled)return;showErr("");addLine("user",v);msgEl.value="";sendBtn.disabled=true;sendBtn.textContent="Working";showThinking();tcJson("/tasmoclaw/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:v})}).then(x=>{hideThinking();if(x.tool_trace)addLine("tool",x.tool_trace);if(x.content)addLine(x.approval_required?"approval":"assistant",x.content);if(x.error)showErr(x.error);showPending(x);refreshStatus();}).catch(e=>{hideThinking();showErr(String(e));}).finally(()=>{sendBtn.disabled=false;sendBtn.textContent="Send";});}sendBtn.onclick=()=>send();msgEl.addEventListener("keydown",ev=>{if(ev.key=="Enter"&&!ev.shiftKey){ev.preventDefault();send();}});document.getElementById("tc_clear").onclick=()=>tcJson("/tasmoclaw/api/clear",{method:"POST"}).then(_=>refreshAll());document.getElementById("tc_approve").onclick=()=>{showThinking();tcJson("/tasmoclaw/api/approve",{method:"POST"}).then(x=>{hideThinking();if(x.result)addLine("assistant",JSON.stringify(x.result));if(x.error)showErr(x.error);refreshAll();}).catch(e=>{hideThinking();showErr(String(e));});};document.getElementById("tc_reject").onclick=()=>tcJson("/tasmoclaw/api/reject",{method:"POST"}).then(_=>refreshAll());refreshAll();</script>')
    webserver.content_stop()
  end
end

var tasmoclaw_ui = module("tasmoclaw_ui")
tasmoclaw_ui.create = def()
  return TasmoClawUI()
end
return tasmoclaw_ui
