import string
import path
import json
import tasmoclaw_util
import tasmoclaw_commands

class TasmoClawTools
  var tool_defs, store

  def init(store)
    self.store = store

    self.tool_defs = {
      'tasmota_status':{'approval':false,'desc':'Read memory/wifi/arch/sensors and Status 0'},
      'tasmota_cmd_read':{'approval':false,'desc':'Run clearly read-only Tasmota command, including Rule1/Rule2/Rule3 reads. Rules is mapped to all rule slots.'},
      'device_read':{'approval':false,'desc':'Read sensors, power state, filesystem/SD status, memory, and Wi-Fi in one compact call'},
      'sensor_read':{'approval':false,'desc':'Read I2C scan and Status 8 sensor data'},
      'power_read':{'approval':false,'desc':'Read Power, Power1, Power2, and Status 0 power state'},
      'file_read':{'approval':false,'desc':'Read text file with byte limit. Supports sd:/path and flash:/path prefixes.'},
      'file_list':{'approval':false,'desc':'List files. Supports sd:/path and flash:/path prefixes.'},
      'ufs_info':{'approval':false,'desc':'Read Tasmota UFS/SD card filesystem type, size, free space, and root listing'},
      'sd_markdown_read':{'approval':false,'desc':'Read a markdown file from the mounted SD card'},
      'sd_markdown_list':{'approval':false,'desc':'List markdown files in the mounted SD card root'},
      'berry_program_read':{'approval':false,'desc':'Read a Berry program file'},
      'berry_program_explain':{'approval':false,'desc':'Read a Berry program so TasmoClaw can explain it'},
      'berry_check':{'approval':false,'desc':'Check berry syntax availability'},
      'command_catalog_search':{'approval':false,'desc':'Search TasmoClaw command families and examples before building an unfamiliar Tasmota command'},
      'command_build':{'approval':false,'desc':'Build and safety-classify a Tasmota command from structured args without executing it'},
      'command_run':{'approval':true,'desc':'Execute a safety-classified Tasmota command; read-only commands run without approval, actions/writes require approval'},
      'command_sequence_run':{'approval':true,'desc':'Execute a sequence of built Tasmota commands in order; read-only sequences run without approval, mixed/action sequences require one approval'},
      'audio_rtttl_play':{'approval':true,'desc':'Play audio using I2SRtttl. Prefer args.rtttl with a complete RTTTL string generated by the model; args.preset supports happy_birthday, happy, success, ok, error, startup, mario, scale, twinkle, and ode.'},
      'audio_file_play':{'approval':true,'desc':'Play or loop an audio file or URL using I2SPlay/I2SLoop. Supports sd:/ and flash:/ paths.'},
      'audio_say':{'approval':true,'desc':'Speak text using I2SSay when audio output supports it'},
      'audio_control':{'approval':true,'desc':'Control I2S audio: stop, pause, resume, gain/volume, beep, codec status, time, or record'},
      'display_control':{'approval':true,'desc':'Show text on the display using DisplayText'},
      'power_control':{'approval':true,'desc':'Read, turn on/off, or toggle Power/Power1/Power2 channels with dynamic approval'},
      'rule_control':{'approval':true,'desc':'Read, enable, disable, clear, or set Tasmota rules with dynamic approval'},
      'light_control':{'approval':true,'desc':'Read or control Tasmota lights: on/off/toggle, dimmer, color, CT, white, scheme, fade, speed'},
      'mqtt_control':{'approval':true,'desc':'Read MQTT config or publish MQTT messages with dynamic approval'},
      'telemetry_control':{'approval':true,'desc':'Read or set TelePeriod and log levels such as WebLog, SerialLog, and SysLog'},
      'network_control':{'approval':true,'desc':'Read or change Wi-Fi/network/time settings with dynamic approval'},
      'system_control':{'approval':true,'desc':'Read state/status or run system Event, Backlog, module/template, restart when explicitly confirmed'},
      'timer_control':{'approval':true,'desc':'Read or set Timers, TimerN, RuleTimerN, and PulseTimeN'},
      'filesystem_control':{'approval':true,'desc':'Read UFS status/list files or run UFS file actions such as mkdir, delete, rename, run with approval'},
      'tasmota_cmd':{'approval':true,'desc':'Execute Tasmota command'},
      'file_write':{'approval':true,'desc':'Write file content. Supports sd:/path and flash:/path prefixes.'},
      'sd_markdown_write':{'approval':true,'desc':'Write a markdown file such as memory.md, agent.md, soul.md, or user.md to the mounted SD card'},
      'berry_program_write':{'approval':true,'desc':'Write a Berry program to /tasmoclaw/berry/ or the workspace fallback'},
      'berry_program_run':{'approval':true,'desc':'Load and run a Berry program file'},
      'berry_skill_template':{'approval':false,'desc':'Return a reusable Berry command/skill template without writing it'},
      'berry_skill_create':{'approval':true,'desc':'Create a reusable Berry skill file that registers a Tasmota command'},
      'berry_skill_run':{'approval':true,'desc':'Load a Berry skill file so its command becomes available'},
      'berry_skill_explain':{'approval':false,'desc':'Read a Berry skill file so TasmoClaw can explain how it works'},
      'berry_load':{'approval':true,'desc':'load(path)'},
      'berry_compile':{'approval':true,'desc':'tasmota.compile(path)'},
      'rule_apply':{'approval':true,'desc':'Apply and optionally enable rule'},
      'rule_clear':{'approval':true,'desc':'Disable and clear a rule slot'},
      'display_message':{'approval':true,'desc':'DisplayText message'},
      'create_demo_berry':{'approval':true,'desc':'Create demo Berry command file'}
    }
  end

  def registry()
    return self.tool_defs
  end

  def tool_lines()
    var out = ''
    for k:self.tool_defs.keys()
      out += '- ' + k + ': ' + self.tool_defs[k]['desc'] + '\n'
    end
    return out
  end

  def requires_approval(name)
    if self.tool_defs.find(name) != nil
      return self.tool_defs[name]['approval']
    end
    return true
  end

  def with_family(args, family)
    var out = {}
    if args != nil
      try
        for k:args.keys()
          out[k] = args[k]
        end
      except .. as e,m
      end
    end
    out['family'] = family
    return out
  end

  def built_command_requires_approval(args, family)
    var a = self.with_family(args, family)
    var b = tasmoclaw_commands.build(a)
    if b.find('ok') == true
      return b.find('safety') != 'read'
    end
    return true
  end

  def requires_approval_for(name, args)
    if args == nil
      args = {}
    end

    if name == 'command_run'
      var b = tasmoclaw_commands.build(args)
      if b.find('ok') == true
        return b.find('safety') != 'read'
      end
      return true
    elif name == 'command_sequence_run'
      return self.sequence_requires_approval(args)
    elif name == 'power_control'
      var action = args.find('action')
      if action == nil || action == ''
        action = 'read'
      end
      action = string.tolower(str(action))
      return !(action == 'read' || action == 'status' || action == 'state')
    elif name == 'rule_control'
      var ra = args.find('action')
      if ra == nil || ra == ''
        ra = 'read'
      end
      ra = string.tolower(str(ra))
      return !(ra == 'read' || ra == 'list' || ra == 'show' || ra == 'status')
    elif name == 'light_control'
      return self.built_command_requires_approval(args, 'light')
    elif name == 'mqtt_control'
      return self.built_command_requires_approval(args, 'mqtt')
    elif name == 'telemetry_control'
      return self.built_command_requires_approval(args, 'telemetry')
    elif name == 'network_control'
      return self.built_command_requires_approval(args, 'network')
    elif name == 'system_control'
      return self.built_command_requires_approval(args, 'system')
    elif name == 'timer_control'
      return self.built_command_requires_approval(args, 'timer')
    elif name == 'filesystem_control'
      return self.built_command_requires_approval(args, 'filesystem')
    end

    return self.requires_approval(name)
  end

  def get_command_arg(args)
    var c = args.find('command')
    if c == nil || c == '' c = args.find('cmd') end
    if c == nil || c == '' c = args.find('cmnd') end
    return c
  end

  def run(name, args)
    if args == nil
      args = {}
    end

    if name=='tasmota_status' return self.run_status(args) end
    if name=='tasmota_cmd_read' return self.run_cmd_read(args) end
    if name=='device_read' return self.device_read(args) end
    if name=='sensor_read' return self.sensor_read(args) end
    if name=='power_read' return self.power_read(args) end
    if name=='file_read' return self.file_read(args) end
    if name=='file_list' return self.file_list(args) end
    if name=='ufs_info' return self.ufs_info(args) end
    if name=='sd_markdown_read' return self.sd_markdown_read(args) end
    if name=='sd_markdown_list' return self.sd_markdown_list(args) end
    if name=='berry_program_read' return self.berry_program_read(args) end
    if name=='berry_program_explain' return self.berry_program_explain(args) end
    if name=='berry_check' return {'ok':true,'result':'syntax-check requires compile approval on this build'} end
    if name=='command_catalog_search' return self.command_catalog_search(args) end
    if name=='command_build' return self.command_build(args) end
    if name=='command_run' return self.command_run(args) end
    if name=='command_sequence_run' return self.command_sequence_run(args) end
    if name=='audio_rtttl_play' return self.audio_rtttl_play(args) end
    if name=='audio_file_play' return self.audio_file_play(args) end
    if name=='audio_say' return self.audio_say(args) end
    if name=='audio_control' return self.audio_control(args) end
    if name=='display_control' return self.display_control(args) end
    if name=='power_control' return self.power_control(args) end
    if name=='rule_control' return self.rule_control(args) end
    if name=='light_control' return self.light_control(args) end
    if name=='mqtt_control' return self.mqtt_control(args) end
    if name=='telemetry_control' return self.telemetry_control(args) end
    if name=='network_control' return self.network_control(args) end
    if name=='system_control' return self.system_control(args) end
    if name=='timer_control' return self.timer_control(args) end
    if name=='filesystem_control' return self.filesystem_control(args) end
    if name=='tasmota_cmd' return self.tasmota_cmd(args) end
    if name=='file_write' return self.file_write(args) end
    if name=='sd_markdown_write' return self.sd_markdown_write(args) end
    if name=='berry_program_write' return self.berry_program_write(args) end
    if name=='berry_program_run' return self.berry_program_run(args) end
    if name=='berry_skill_template' return self.berry_skill_template(args) end
    if name=='berry_skill_create' return self.berry_skill_create(args) end
    if name=='berry_skill_run' return self.berry_skill_run(args) end
    if name=='berry_skill_explain' return self.berry_skill_explain(args) end
    if name=='berry_load' return self.berry_load(args) end
    if name=='berry_compile' return self.berry_compile(args) end
    if name=='rule_apply' return self.rule_apply(args) end
    if name=='rule_clear' return self.rule_clear(args) end
    if name=='display_message' return self.display_message(args) end
    if name=='create_demo_berry' return self.create_demo_berry(args) end

    return {'ok':false,'error':'Unknown tool: ' + name}
  end

  def normalize_name(name, ext)
    if name == nil || name == ''
      name = 'memory'
    end

    var n = str(name)
    n = string.replace(n, '/', '_')
    n = string.replace(n, '\\', '_')
    n = string.replace(n, ' ', '_')
    n = string.replace(n, '..', '_')

    var has_dot = string.find(n, '.')
    if ext == '.md' && has_dot != nil && has_dot >= 0
      return n
    end

    var ei = string.find(n, ext)
    if ei == nil || ei < 0 || ei != size(n) - size(ext)
      n += ext
    end

    return n
  end

  def sd_mounted()
    try
      var r = tasmota.cmd('UfsType', true)
      var t = r.find('UfsType')
      if t == 1
        return true
      end
      var ts = str(t)
      if string.find(ts, '1') != nil && string.find(ts, '1') >= 0
        return true
      end
    except .. as e,m
    end
    return false
  end

  def has_fs_prefix(p)
    if p == nil
      return false
    end

    var l = string.tolower(str(p))
    var sd = string.find(l, 'sd:')
    var flash = string.find(l, 'flash:')
    return (sd != nil && sd == 0) || (flash != nil && flash == 0)
  end

  def prefixed_path(fs_name, p)
    if p == nil || p == ''
      p = '/'
    end

    if self.has_fs_prefix(p)
      return p
    end

    if p[0..0] != '/'
      p = '/' + p
    end

    return fs_name + ':' + p
  end

  def ufs_read_file(p, max_bytes)
    if !global.contains('tasmo_ufs_read')
      return {'ok':false,'error':'native UFS read helper tasmo_ufs_read is unavailable in this firmware'}
    end

    try
      var raw = global.tasmo_ufs_read(p, max_bytes)
      return json.load(raw)
    except .. as e,m
      return {'ok':false,'error':'native SD read failed: '+str(m)}
    end
  end

  def ufs_write_file(p, content)
    if !global.contains('tasmo_ufs_write')
      return {'ok':false,'error':'native UFS write helper tasmo_ufs_write is unavailable in this firmware'}
    end

    try
      var raw = global.tasmo_ufs_write(p, content)
      return json.load(raw)
    except .. as e,m
      return {'ok':false,'error':'native SD write failed: '+str(m)}
    end
  end

  def ufs_list_dir(p)
    if !global.contains('tasmo_ufs_list')
      return {'ok':false,'error':'native UFS list helper tasmo_ufs_list is unavailable in this firmware'}
    end

    try
      var raw = global.tasmo_ufs_list(p)
      return json.load(raw)
    except .. as e,m
      return {'ok':false,'error':'native SD list failed: '+str(m)}
    end
  end

  def power_snapshot()
    var out = {}
    try
      var status0 = tasmota.cmd('Status 0', true)
      out['status0'] = status0
      var sts = status0.find('StatusSTS')
      if sts != nil
        out['POWER1'] = sts.find('POWER1')
        out['POWER2'] = sts.find('POWER2')
        out['Power'] = sts.find('Power')
        if out['Power'] == nil && (out['POWER1'] != nil || out['POWER2'] != nil)
          out['Power'] = 'POWER1=' + str(out['POWER1']) + ', POWER2=' + str(out['POWER2'])
        end
      end
    except .. as e,m
      out['status0_error'] = str(m)
    end
    return out
  end

  def berry_path(name)
    var n = self.normalize_name(name, '.be')
    if self.store != nil && self.store.workspace_fallback
      return '/tasmoclaw_demo_' + n
    end
    return '/tasmoclaw/berry/' + n
  end

  def markdown_path(name)
    return '/' + self.normalize_name(name, '.md')
  end

  def run_status(args)
    var out = {
      'memory':tasmota.memory(),
      'wifi':tasmota.wifi(),
      'arch':tasmota.arch()
    }

    try
      out['sensors']=tasmota.read_sensors(false)
    except .. as e,m
    end

    try
      out['status0']=tasmota.cmd('Status 0', true)
    except .. as e,m
    end

    return {'ok':true, 'result':out}
  end

  def run_cmd_read(args)
    var c = self.get_command_arg(args)

    if c == nil || c == ''
      return {'ok':false,'error':'missing command'}
    end

    var lower = string.tolower(c)

    var first_space = string.find(lower, ' ')
    var first = lower
    var rest = ''

    if first_space != nil && first_space >= 0
      first = lower[0..first_space-1]
      rest = lower[first_space+1..size(lower)-1]
    end

    var cls = tasmoclaw_commands.classify_command(c)
    if cls.find('ok') != true || cls.find('safety') != 'read'
      return {'ok':false,'error':'command is not clearly read-only; request command_run or tasmota_cmd with approval','classification':cls}
    end

    try
      if first == 'rules'
        return {
          'ok':true,
          'result':{
            'Rule1':tasmota.cmd('Rule1', true),
            'Rule2':tasmota.cmd('Rule2', true),
            'Rule3':tasmota.cmd('Rule3', true)
          }
        }
      end
      return {'ok':true,'result':tasmota.cmd(c, true)}
    except .. as e,m
      return {'ok':false,'error':'command failed: '+str(m)}
    end
  end

  def sensor_read(args)
    var out = {}

    try
      out['i2cscan'] = tasmota.cmd('I2CScan', true)
    except .. as e,m
      out['i2cscan_error'] = str(m)
    end

    try
      out['status8'] = tasmota.cmd('Status 8', true)
    except .. as e2,m2
      out['status8_error'] = str(m2)
    end

    try
      out['sensors'] = tasmota.read_sensors(false)
    except .. as e4,m4
      out['sensors_error'] = str(m4)
    end

    return {'ok':true,'result':out}
  end

  def device_read(args)
    var out = {
      'memory':tasmota.memory(),
      'wifi':tasmota.wifi(),
      'sd_mounted':self.sd_mounted()
    }

    try
      out['i2cscan'] = tasmota.cmd('I2CScan', true)
    except .. as e,m
      out['i2cscan_error'] = str(m)
    end

    try
      out['status8'] = tasmota.cmd('Status 8', true)
    except .. as e1,m1
      out['status8_error'] = str(m1)
    end

    try
      out['power'] = self.power_snapshot()
    except .. as e2,m2
      out['power_error'] = str(m2)
    end

    try
      out['ufs'] = tasmota.cmd('Ufs', true)
    except .. as e5,m5
      out['ufs_error'] = str(m5)
    end

    return {
      'ok':true,
      'result':out
    }
  end

  def power_read(args)
    var out = self.power_snapshot()

    return {'ok':true,'result':out}
  end

  def command_catalog_search(args)
    return tasmoclaw_commands.search(args)
  end

  def command_build(args)
    return tasmoclaw_commands.build(args)
  end

  def run_built_command(args, allow_dangerous)
    var built = tasmoclaw_commands.build(args)
    if built.find('ok') != true
      return built
    end

    var c = built.find('command')
    if c == nil || c == ''
      return {'ok':false,'error':'missing built command'}
    end

    var safety = built.find('safety')
    if safety == 'dangerous' && allow_dangerous != true
      return {
        'ok':false,
        'error':'Refusing high-impact command without explicit confirm:true',
        'command':c,
        'safety':safety,
        'reason':built.find('reason')
      }
    end

    try
      var read_only = safety == 'read'
      return {
        'ok':true,
        'command':c,
        'safety':safety,
        'reason':built.find('reason'),
        'result':tasmota.cmd(c, read_only)
      }
    except .. as e,m
      return {'ok':false,'error':'command failed: '+str(m),'command':c,'safety':safety}
    end
  end

  def command_run(args)
    return self.run_built_command(args, args.find('confirm') == true)
  end

  def sequence_items(args)
    if args == nil
      return nil
    end

    var items = args.find('items')
    if items == nil
      items = args.find('steps')
    end
    if items == nil
      items = args.find('commands')
    end
    if type(items) == 'string'
      items = [items]
    end
    return items
  end

  def sequence_item_args(item)
    try
      if item.find('command') != nil || item.find('cmd') != nil || item.find('family') != nil || item.find('tool') != nil
        return item
      end
    except .. as e,m
    end
    return {'command':str(item)}
  end

  def sequence_requires_approval(args)
    var items = self.sequence_items(args)
    if items == nil
      return true
    end

    for item:items
      var step = self.sequence_item_args(item)
      if step == nil
        return true
      end
      try
        var built = tasmoclaw_commands.build(step)
        if built.find('ok') != true
          return true
        end
        if built.find('safety') != 'read'
          return true
        end
      except .. as e,m
        return true
      end
    end
    return false
  end

  def command_sequence_run(args)
    var items = self.sequence_items(args)
    if items == nil
      return {'ok':false,'error':'missing items/steps/commands'}
    end

    var results = []
    var idx = 0
    var continue_on_error = args.find('continue_on_error') == true
    var sequence_confirm = args.find('confirm') == true

    for item:items
      var step = self.sequence_item_args(item)
      if step == nil
        var bad = {'ok':false,'error':'invalid sequence item','index':idx,'item':str(item)}
        results.push(bad)
        return {'ok':false,'results':results,'stopped_at':idx,'error':'invalid sequence item'}
      end

      var r = nil
      try
        r = self.run_built_command(step, sequence_confirm || step.find('confirm') == true)
      except .. as e,m
        var bad2 = {'ok':false,'error':'invalid sequence item: '+str(m),'index':idx,'item':str(item)}
        results.push(bad2)
        return {'ok':false,'results':results,'stopped_at':idx,'error':bad2.find('error')}
      end
      r['index'] = idx
      results.push(r)
      if r.find('ok') != true && !continue_on_error
        return {'ok':false,'results':results,'stopped_at':idx,'error':r.find('error')}
      end
      idx += 1
    end

    return {'ok':true,'results':results,'count':idx}
  end

  def audio_rtttl_play(args)
    if args == nil
      args = {}
    end
    args['family'] = 'audio'
    args['action'] = 'rtttl'
    return self.run_built_command(args, true)
  end

  def audio_file_play(args)
    if args == nil
      args = {}
    end
    args['family'] = 'audio'
    var action = args.find('action')
    if action == nil || action == ''
      action = 'play'
    end
    args['action'] = action
    return self.run_built_command(args, true)
  end

  def audio_say(args)
    if args == nil
      args = {}
    end
    args['family'] = 'audio'
    args['action'] = 'say'
    return self.run_built_command(args, true)
  end

  def audio_control(args)
    if args == nil
      args = {}
    end
    args['family'] = 'audio'
    if args.find('action') == nil || args.find('action') == ''
      args['action'] = 'stop'
    end
    return self.run_built_command(args, true)
  end

  def display_control(args)
    if args == nil
      args = {}
    end
    args['family'] = 'display'
    return self.run_built_command(args, true)
  end

  def power_control(args)
    if args == nil
      args = {}
    end
    args['family'] = 'power'
    var action = args.find('action')
    if action == nil || action == ''
      action = 'read'
    end
    args['action'] = action
    return self.run_built_command(args, true)
  end

  def rule_control(args)
    if args == nil
      args = {}
    end

    var action = args.find('action')
    if action == nil || action == ''
      action = 'read'
    end
    action = string.tolower(str(action))

    if (args.find('rule') == nil || args.find('rule') == '') && args.find('slot') != nil
      args['rule'] = args.find('slot')
    end

    if action == 'clear' || action == 'delete' || action == 'remove'
      return self.rule_clear(args)
    elif action == 'set' || action == 'apply' || action == 'write'
      return self.rule_apply(args)
    end

    var rule_name = args.find('rule')
    if rule_name == nil || rule_name == ''
      rule_name = args.find('slot')
    end
    if rule_name == nil || rule_name == ''
      rule_name = 'Rules'
    end
    if string.tolower(str(rule_name)) == 'rules'
      return self.run_cmd_read({'command':'Rules'})
    end

    args['family'] = 'rules'
    args['action'] = action
    return self.run_built_command(args, true)
  end

  def light_control(args)
    return self.run_built_command(self.with_family(args, 'light'), true)
  end

  def mqtt_control(args)
    return self.run_built_command(self.with_family(args, 'mqtt'), true)
  end

  def telemetry_control(args)
    return self.run_built_command(self.with_family(args, 'telemetry'), true)
  end

  def network_control(args)
    return self.run_built_command(self.with_family(args, 'network'), args != nil && args.find('confirm') == true)
  end

  def system_control(args)
    return self.run_built_command(self.with_family(args, 'system'), args != nil && args.find('confirm') == true)
  end

  def timer_control(args)
    return self.run_built_command(self.with_family(args, 'timer'), true)
  end

  def filesystem_control(args)
    return self.run_built_command(self.with_family(args, 'filesystem'), true)
  end

  def tasmota_cmd(args)
    var c = self.get_command_arg(args)

    if c == nil || c == ''
      return {'ok':false,'error':'missing command'}
    end

    try
      return {'ok':true,'result':tasmota.cmd(c, false)}
    except .. as e,m
      return {'ok':false,'error':'command failed: '+str(m)}
    end
  end

  def file_read(args)
    var p=args.find('path')
    var m=args.find('max_bytes')

    if p == nil || p == ''
      return {'ok':false,'error':'missing path'}
    end

    if m==nil
      m=4096
    end

    if m<1
      m=4096
    end

    if m>16384
      return {'ok':false,'error':'max_bytes too large'}
    end

    if self.has_fs_prefix(p)
      return self.ufs_read_file(p, m)
    end

    var berry_error = nil
    try
      if path.exists(p) == true
        var f=open(p,'r')
        var s=f.read(m)
        f.close()

        return {'ok':true,'path':p,'bytes':size(s),'result':s,'fs':'flash'}
      end
    except .. as e,msg
      berry_error = str(msg)
    end

    var r = self.ufs_read_file(p, m)
    if r['ok']
      return r
    end
    if berry_error != nil
      r['flash_error'] = berry_error
    end
    return r
  end

  def file_write(args)
    var p=args.find('path')
    var c=args.find('content')

    if p == nil || p == ''
      return {'ok':false,'error':'missing path'}
    end

    if c == nil
      c = ''
    end

    if self.has_fs_prefix(p)
      return self.ufs_write_file(p, c)
    end

    var berry_error = nil
    try
      var f=open(p,'w')
      f.write(c)
      f.close()
      return {'ok':true,'path':p,'bytes':size(c),'fs':'flash'}
    except .. as e,msg
      berry_error = str(msg)
    end

    var r = self.ufs_write_file(p, c)
    if r['ok']
      return r
    end
    r['flash_error'] = berry_error
    return r
  end

  def file_list(args)
    var p = args.find('path')
    if p == nil || p == ''
      p = '/'
    end

    if self.has_fs_prefix(p)
      return self.ufs_list_dir(p)
    end

    try
      return {'ok':true,'path':p,'result':tasmota.cmd('UfsList ' + p, true)}
    except .. as e,m
      var r = self.ufs_list_dir(p)
      if r['ok']
        return r
      end
      return {'ok':false,'error':'file list failed: '+str(m),'native':r}
    end
  end

  def ufs_info(args)
    var out = {}

    try
      out['ufs'] = tasmota.cmd('Ufs', true)
    except .. as e,m
      out['ufs_error'] = str(m)
    end

    try
      out['type'] = tasmota.cmd('UfsType', true)
    except .. as e1,m1
      out['type_error'] = str(m1)
    end

    try
      out['size'] = tasmota.cmd('UfsSize', true)
    except .. as e2,m2
      out['size_error'] = str(m2)
    end

    try
      out['free'] = tasmota.cmd('UfsFree', true)
    except .. as e3,m3
      out['free_error'] = str(m3)
    end

    try
      out['list'] = tasmota.cmd('UfsList', true)
    except .. as e4,m4
      out['list_error'] = str(m4)
    end
    out['sd_mounted'] = self.sd_mounted()
    if out['sd_mounted']
      out['sd_list'] = self.ufs_list_dir('sd:/')
    end
    out['flash_list'] = self.ufs_list_dir('flash:/')

    return {'ok':true,'result':out}
  end

  def sd_markdown_read(args)
    if !self.sd_mounted()
      return {'ok':false,'error':'SD card is not mounted. Check USE_SDCARD and SDIO pins CMD=GPIO21, CLK=GPIO38, D0=GPIO39.'}
    end

    var n = args.find('name')
    if n == nil || n == ''
      n = args.find('filename')
    end
    if n == nil || n == ''
      n = args.find('path')
    end

    var p = self.prefixed_path('sd', self.markdown_path(n))
    return self.ufs_read_file(p, args.find('max_bytes') == nil ? 8192 : args.find('max_bytes'))
  end

  def sd_markdown_write(args)
    if !self.sd_mounted()
      return {'ok':false,'error':'SD card is not mounted. Check USE_SDCARD and SDIO pins CMD=GPIO21, CLK=GPIO38, D0=GPIO39.'}
    end

    var n = args.find('name')
    if n == nil || n == ''
      n = args.find('filename')
    end
    if n == nil || n == ''
      n = args.find('path')
    end

    var p = self.prefixed_path('sd', self.markdown_path(n))
    var c = args.find('content')
    if c == nil
      c = ''
    end

    var r = self.ufs_write_file(p, c)
    if r['ok']
      r['sd'] = true
    end
    return r
  end

  def sd_markdown_list(args)
    if !self.sd_mounted()
      return {'ok':false,'error':'SD card is not mounted. Check USE_SDCARD and SDIO pins CMD=GPIO21, CLK=GPIO38, D0=GPIO39.'}
    end

    try
      return self.ufs_list_dir('sd:/')
    except .. as e,m
      return {'ok':false,'error':'SD markdown list failed: '+str(m)}
    end
  end

  def berry_program_write(args)
    var p = args.find('path')
    if p == nil || p == ''
      p = self.berry_path(args.find('name'))
    end

    var c = args.find('content')
    if c == nil || c == ''
      c = "def hello_world_cmd(cmd, idx, payload, payload_json)\n"
      c += "  tasmota.resp_cmnd('{\"HelloWorld\":\"ok\"}')\n"
      c += "end\n\n"
      c += "tasmota.add_cmd('HelloWorld', hello_world_cmd)\n"
      c += "print('Hello World from TasmoClaw')\n"
    end

    var r = self.file_write({'path':p,'content':c})
    if r['ok']
      r['berry_program'] = true
    end
    return r
  end

  def berry_program_read(args)
    var p = args.find('path')
    if p == nil || p == ''
      p = self.berry_path(args.find('name'))
    end
    return self.file_read({'path':p,'max_bytes':args.find('max_bytes') == nil ? 8192 : args.find('max_bytes')})
  end

  def berry_program_explain(args)
    var r = self.berry_program_read(args)
    if r['ok']
      r['instruction'] = 'Explain this Berry source to the user, including commands it registers, filesystem side effects, and how to run it.'
    end
    return r
  end

  def berry_program_run(args)
    var p = args.find('path')
    if p == nil || p == ''
      p = self.berry_path(args.find('name'))
    end
    return self.berry_load({'path':p})
  end

  def safe_skill_token(value, fallback)
    if value == nil || value == ''
      value = fallback
    end
    var s = str(value)
    for bad:['/','\\',' ','-','.',':',';','; ',',','"','\'','`','(',')','[',']','{','}','=','+','*','&','?','!','#']
      s = string.replace(s, bad, '_')
    end
    while string.find(s, '__') != nil && string.find(s, '__') >= 0
      s = string.replace(s, '__', '_')
    end
    if s == nil || s == '' || s == '_'
      s = fallback
    end
    return s
  end

  def berry_skill_source(args)
    var name = self.safe_skill_token(args.find('name'), 'tasmo_skill')
    var command = self.safe_skill_token(args.find('command'), name)
    var fn = string.tolower(command) + '_cmd'
    fn = self.safe_skill_token(fn, 'tasmo_skill_cmd')
    var desc = args.find('description')
    if desc == nil
      desc = 'TasmoClaw generated Berry skill'
    end

    var c = "import string\n\n"
    c += "# " + str(desc) + "\n"
    c += "def _tc_escape(v)\n"
    c += "  var s = str(v)\n"
    c += "  s = string.replace(s, '\\\\', '\\\\\\\\')\n"
    c += "  s = string.replace(s, '\"', '\\\\\"')\n"
    c += "  s = string.replace(s, '\\n', '\\\\n')\n"
    c += "  s = string.replace(s, '\\r', '\\\\r')\n"
    c += "  return s\n"
    c += "end\n\n"
    c += "def " + fn + "(cmd, idx, payload, payload_json)\n"
    c += "  var p = _tc_escape(payload)\n"
    c += "  tasmota.resp_cmnd('{\"" + command + "\":{\"ok\":true,\"payload\":\"' + p + '\"}}')\n"
    c += "end\n\n"
    c += "tasmota.add_cmd('" + command + "', " + fn + ")\n"
    c += "print('TasmoClaw Berry skill " + command + " loaded')\n"
    return {'name':name,'command':command,'source':c}
  end

  def berry_skill_template(args)
    if args == nil
      args = {}
    end
    var t = self.berry_skill_source(args)
    return {
      'ok':true,
      'name':t.find('name'),
      'command':t.find('command'),
      'content':t.find('source'),
      'usage':'Save with berry_skill_create, load with berry_skill_run, then call the registered Tasmota command from console or TasmoClaw.'
    }
  end

  def berry_skill_create(args)
    if args == nil
      args = {}
    end
    var p = args.find('path')
    var content = args.find('content')
    var t = self.berry_skill_source(args)
    if p == nil || p == ''
      p = self.berry_path(t.find('name'))
    end
    if content == nil || content == ''
      content = args.find('code')
    end
    if content == nil || content == ''
      content = t.find('source')
    end

    var r = self.file_write({'path':p,'content':content})
    if r.find('ok') == true
      r['berry_skill'] = true
      r['command'] = t.find('command')
      if args.find('autoload') == true || args.find('load') == true
        r['load'] = self.berry_load({'path':p})
      end
    end
    return r
  end

  def berry_skill_run(args)
    if args == nil
      args = {}
    end
    return self.berry_program_run(args)
  end

  def berry_skill_explain(args)
    if args == nil
      args = {}
    end
    var r = self.berry_program_read(args)
    if r.find('ok') == true
      r['instruction'] = 'Explain this reusable Berry skill, including the Tasmota command it registers, how to load it, and how to call it.'
      r['berry_skill'] = true
    end
    return r
  end

  def berry_load(args)
    var p=args.find('path')

    if p == nil || p == ''
      return {'ok':false,'error':'missing path'}
    end

    try
      var r = load(p)
      return {'ok':true,'result':str(r)}
    except .. as e,m
      return {'ok':false,'error':'load failed: '+str(m)}
    end
  end

  def berry_compile(args)
    var p=args.find('path')

    if p == nil || p == ''
      return {'ok':false,'error':'missing path'}
    end

    try
      var r = tasmota.compile(p)
      return {'ok':true,'result':str(r)}
    except .. as e,m
      return {'ok':false,'error':'compile failed: '+str(m)}
    end
  end

  def rule_apply(args)
    var r=args.find('rule')
    var d=args.find('definition')

    if r == nil || r == ''
      r = 'Rule1'
    end
    if r == '1' || r == '2' || r == '3'
      r = 'Rule' + str(r)
    end

    if d == nil || d == ''
      return {'ok':false,'error':'missing definition'}
    end

    try
      var cmd1 = r + ' ' + d
      var r1 = tasmota.cmd(cmd1, false)

      var result = {
        'set_command':cmd1,
        'set':r1
      }

      if args.find('enable') == true
        var cmd2 = r + ' 1'
        var r2 = tasmota.cmd(cmd2, false)

        result['enable_command'] = cmd2
        result['enable'] = r2
      end

      if args.find('start_timer1') == true
        var seconds = args.find('timer1_seconds')
        if seconds == nil || seconds < 1
          seconds = 5
        end
        var cmd3 = 'RuleTimer1 ' + str(seconds)
        var r3 = tasmota.cmd(cmd3, false)

        result['start_timer_command'] = cmd3
        result['start_timer'] = r3
      end

      return {'ok':true,'result':result}

    except .. as e,m
      return {'ok':false,'error':'rule apply failed: '+str(m)}
    end
  end

  def rule_clear(args)
    var r=args.find('rule')

    if r == nil || r == ''
      r = 'Rule3'
    end
    if r == '1' || r == '2' || r == '3'
      r = 'Rule' + str(r)
    end

    try
      var cmd1 = r + ' 0'
      var r1 = tasmota.cmd(cmd1, false)
      var result = {
        'disable_command':cmd1,
        'disable':r1
      }

      if args.find('stop_timer1') == true
        var cmd_timer = 'RuleTimer1 0'
        result['timer_command'] = cmd_timer
        result['timer'] = tasmota.cmd(cmd_timer, false)
      end

      # Tasmota clears a rule when the payload begins with a double quote.
      var cmd2 = r + ' "'
      var r2 = tasmota.cmd(cmd2, false)
      result['clear_command'] = cmd2
      result['clear'] = r2

      return {'ok':true,'result':result}

    except .. as e,m
      return {'ok':false,'error':'rule clear failed: '+str(m)}
    end
  end

  def display_message(args)
    var msg=args.find('message')

    if msg == nil
      msg = ''
    end

    try
      var r = tasmota.cmd('DisplayText ' + msg, false)
      return {'ok':true,'result':r}
    except .. as e,m
      return {'ok':false,'error':'DisplayText failed; display may not be configured: '+str(m)}
    end
  end

  def create_demo_berry(args)
    var n=args.find('name')

    if n == nil || n == ''
      n = 'ai_status'
    end

    n = string.replace(n, '/', '_')
    n = string.replace(n, '\\', '_')
    n = string.replace(n, ' ', '_')

    var p = self.berry_path(n)

    var c = "import string\n\n"
    c += "def ai_status_cmd(cmd, idx, payload)\n"
    c += "  var mem = str(tasmota.memory())\n"
    c += "  var wifi = str(tasmota.wifi())\n"
    c += "  mem = string.replace(mem, '\"', '\\\\\"')\n"
    c += "  wifi = string.replace(wifi, '\"', '\\\\\"')\n"
    c += "  var out = '{\"AIStatus\":{\"memory\":\"' + mem + '\",\"wifi\":\"' + wifi + '\"}}'\n"
    c += "  tasmota.resp_cmnd(out)\n"
    c += "end\n\n"
    c += "tasmota.add_cmd('AIStatus', ai_status_cmd)\n"

    var r = self.file_write({'path':p,'content':c})

    if r['ok']
      r['fallback_workspace'] = self.store != nil ? self.store.workspace_fallback : false
    end

    return r
  end

end

var tasmoclaw_tools = module("tasmoclaw_tools")

tasmoclaw_tools.create = def(store)
  return TasmoClawTools(store)
end

return tasmoclaw_tools
