import webserver

class TasmoClawUI
  def chat_page()
    webserver.content_start('TasmoClaw')
    webserver.content_send_style()
    webserver.content_send('<style>.tc-box{background:#111;color:#ddd;padding:8px;border-radius:6px;min-height:240px;white-space:pre-wrap;overflow:auto;text-align:left}.tc-badge{display:inline-block;padding:2px 6px;border-radius:10px;background:#333;color:#eee;font-size:11px;margin:2px}.tc-row{margin:8px 0}.tc-err{color:#f66}.tc-pending{border:1px solid var(--c_frm);padding:8px;margin-top:8px;text-align:left}.tc-pending pre{white-space:pre-wrap;overflow:auto}</style>')
    webserver.content_send('<h2>TasmoClaw</h2><div><span class="tc-badge" id="tc_model"></span><span class="tc-badge" id="tc_endpoint"></span><span class="tc-badge" id="tc_heap"></span><span class="tc-badge" id="tc_wifi"></span></div>')
    webserver.content_send('<p><a href="/tasmoclaw/config"><button>Config</button></a> <button id="tc_clear">Clear</button></p><div id="tc_chat" class="tc-box"></div><div class="tc-row"><textarea id="tc_message" style="width:100%;height:90px"></textarea></div><p><button id="tc_send">Send</button></p><div id="tc_error" class="tc-err"></div><div id="tc_pending" class="tc-pending" style="display:none"><h4>Pending approval</h4><pre id="tc_pending_json"></pre><button id="tc_approve">Approve</button> <button id="tc_reject">Reject</button></div>')
    webserver.content_send('<script>const tcJson=(u,o)=>fetch(u,o).then(r=>r.json());const chatEl=document.getElementById("tc_chat");const sendBtn=document.getElementById("tc_send");const msgEl=document.getElementById("tc_message");const errEl=document.getElementById("tc_error");function addLine(role,text){chatEl.textContent+="["+role+"] "+(text||"")+"\\n";chatEl.scrollTop=chatEl.scrollHeight;}function showErr(t){errEl.textContent=t||"";}function showPending(x){const panel=document.getElementById("tc_pending");const pre=document.getElementById("tc_pending_json");if(!x||!x.pending){panel.style.display="none";pre.textContent="";return;}panel.style.display="block";pre.textContent=JSON.stringify(x.pending,null,2);}function refreshStatus(){tcJson("/tasmoclaw/api/status").then(s=>{if(s.ok){document.getElementById("tc_model").textContent=s.model||"";document.getElementById("tc_endpoint").textContent=s.api_url||"";document.getElementById("tc_heap").textContent="heap:"+JSON.stringify(s.heap);document.getElementById("tc_wifi").textContent="wifi:"+JSON.stringify(s.wifi);}}).catch(e=>showErr(String(e)));}function refreshHistory(){tcJson("/tasmoclaw/api/history").then(x=>{chatEl.textContent="";(x.history||[]).forEach(m=>addLine(m.role,m.content));}).catch(e=>showErr(String(e)));}function refreshPending(){tcJson("/tasmoclaw/api/pending").then(showPending).catch(e=>showErr(String(e)));}function refreshAll(){refreshStatus();refreshHistory();refreshPending();}sendBtn.onclick=()=>{const v=msgEl.value.trim();if(!v)return;showErr("");addLine("user",v);msgEl.value="";sendBtn.disabled=true;tcJson("/tasmoclaw/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:v})}).then(x=>{if(x.content)addLine(x.approval_required?"approval":"assistant",x.content);if(x.error)showErr(x.error);showPending(x);refreshStatus();}).catch(e=>showErr(String(e))).finally(()=>sendBtn.disabled=false);};document.getElementById("tc_clear").onclick=()=>tcJson("/tasmoclaw/api/clear",{method:"POST"}).then(_=>refreshAll());document.getElementById("tc_approve").onclick=()=>tcJson("/tasmoclaw/api/approve",{method:"POST"}).then(x=>{if(x.result)addLine("assistant",JSON.stringify(x.result));if(x.error)showErr(x.error);refreshAll();});document.getElementById("tc_reject").onclick=()=>tcJson("/tasmoclaw/api/reject",{method:"POST"}).then(_=>refreshAll());refreshAll();</script>')
    webserver.content_stop()
  end
end

var tasmoclaw_ui = module("tasmoclaw_ui")
tasmoclaw_ui.create = def()
  return TasmoClawUI()
end
return tasmoclaw_ui
